[package]
name = "winux"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = { version = "0.23", features = ["glow"] }
winapi = { version = "0.3", features = ["winuser", "windef"] }
chrono = "0.4"
dirs = "4.0"
open = "3"
